/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 pols_gtr.glb 
Author: CarEnthusiast (https://sketchfab.com/CarEnthusiast)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/pols-gtr-free-aaaa0a42ff4f4c16aba3803363d7a482
Title: PoLs GTR [Free]
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/3dmodel/pols_gtr.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh geometry={nodes.Mesh1_FrontColor_0.geometry} material={materials.FrontColor} />
        <mesh geometry={nodes.Mesh2_Color_C05_0.geometry} material={materials.Color_C05} />
        <mesh geometry={nodes.Mesh3_FrontColor_0.geometry} material={materials.FrontColor} />
        <mesh geometry={nodes.Mesh4_FrontColor_0.geometry} material={materials.FrontColor} />
        <mesh geometry={nodes.Mesh5_FrontColor_0.geometry} material={materials.FrontColor} />
        <mesh geometry={nodes.Mesh6_FrontColor_0.geometry} material={materials.FrontColor} />
        <mesh geometry={nodes.Mesh7_FrontColor_0.geometry} material={materials.FrontColor} />
        <mesh geometry={nodes.Mesh8_FrontColor_0.geometry} material={materials.FrontColor} />
        <mesh geometry={nodes.Mesh9_FrontColor_0.geometry} material={materials.FrontColor} />
        <mesh geometry={nodes.Mesh10_FrontColor_0.geometry} material={materials.FrontColor} />
        <mesh geometry={nodes.Mesh11_Color_C05_0.geometry} material={materials.Color_C05} />
        <mesh geometry={nodes.Mesh12_r_light_lamp1_0.geometry} material={materials.r_light_lamp1} />
        <mesh geometry={nodes.Mesh13_Color_B06_0.geometry} material={materials.Color_B06} />
        <mesh geometry={nodes.Mesh14_Color_B06_0.geometry} material={materials.Color_B06} />
        <mesh geometry={nodes.Mesh15_Color_B04_0.geometry} material={materials.Color_B04} />
        <mesh geometry={nodes.Mesh16_Color_C05_0.geometry} material={materials.Color_C05} />
        <mesh geometry={nodes.Mesh17_Color_C05_0.geometry} material={materials.Color_C05} />
        <mesh geometry={nodes.Mesh17_Color_B06_0.geometry} material={materials.Color_B06} />
        <mesh geometry={nodes.Mesh18_Color_C05_0.geometry} material={materials.Color_C05} />
        <mesh geometry={nodes.Mesh19_Color_B04_0.geometry} material={materials.Color_B04} />
        <mesh geometry={nodes.Mesh20_Color_C05_0.geometry} material={materials.Color_C05} />
        <mesh geometry={nodes.Mesh21_Color_C05_0.geometry} material={materials.Color_C05} />
        <mesh geometry={nodes.Mesh21_Color_B06_0.geometry} material={materials.Color_B06} />
        <mesh geometry={nodes.Mesh22__1_0.geometry} material={materials.material} />
        <mesh geometry={nodes.Mesh23__1_0.geometry} material={materials.material} />
        <mesh geometry={nodes.Mesh24_Color_C05_0.geometry} material={materials.Color_C05} />
        <mesh geometry={nodes.Mesh24__Color_B01_1_0.geometry} material={materials.Color_B01_1} />
        <mesh geometry={nodes.Mesh24__1_0.geometry} material={materials.material} />
        <mesh geometry={nodes.Mesh24_Color_B06_0.geometry} material={materials.Color_B06} />
        <mesh geometry={nodes.Mesh25__3_0.geometry} material={materials.material_7} />
        <mesh geometry={nodes.Mesh26__3_0.geometry} material={materials.material_7} />
        <mesh geometry={nodes.Mesh27_Color_C05_0.geometry} material={materials.Color_C05} />
        <mesh geometry={nodes.Mesh27_Color_B06_0.geometry} material={materials.Color_B06} />
        <mesh geometry={nodes.Mesh27_FrontColor_0.geometry} material={materials.FrontColor} />
        <mesh geometry={nodes.Mesh27__Color_B01_1_0.geometry} material={materials.Color_B01_1} />
        <mesh geometry={nodes.Mesh28_Color_B01_0.geometry} material={materials.Color_B01} />
        <mesh geometry={nodes.Mesh28_FrontColor_0.geometry} material={materials.FrontColor} />
        <mesh geometry={nodes.Mesh28_Color_B04_0.geometry} material={materials.Color_B04} />
        <mesh geometry={nodes.Mesh29_Color_C05_0.geometry} material={materials.Color_C05} />
        <mesh geometry={nodes.Mesh29_Color_B06_0.geometry} material={materials.Color_B06} />
        <mesh geometry={nodes.Mesh29_Color_B01_0.geometry} material={materials.Color_B01} />
        <mesh geometry={nodes.Mesh29_Color_C03_0.geometry} material={materials.Color_C03} />
        <mesh geometry={nodes.Mesh29__Color_B01_1_0.geometry} material={materials.Color_B01_1} />
        <mesh geometry={nodes.Mesh30_Color_C05_0.geometry} material={materials.Color_C05} />
        <mesh geometry={nodes.Mesh31_FrontColor_0.geometry} material={materials.FrontColor} />
        <mesh geometry={nodes.Mesh32_Color_C03_0.geometry} material={materials.Color_C03} />
        <mesh geometry={nodes.Mesh32_Color_M02_0.geometry} material={materials.Color_M02} />
        <mesh geometry={nodes.Mesh32_Color_M04_0.geometry} material={materials.Color_M04} />
        <mesh geometry={nodes.Mesh33_Color_C02_0.geometry} material={materials.Color_C02} />
        <mesh geometry={nodes.Mesh34__2_0.geometry} material={materials.material_13} />
        <mesh geometry={nodes.Mesh35__2_0.geometry} material={materials.material_13} />
        <mesh geometry={nodes.Mesh36_Color_C01_0.geometry} material={materials.Color_C01} />
        <mesh geometry={nodes.Mesh37_tires_0.geometry} material={materials.tires} />
        <mesh geometry={nodes.Mesh38_wheel2_0.geometry} material={materials.wheel2} />
        <mesh geometry={nodes.Mesh38_wheel1_0.geometry} material={materials.wheel1} />
        <mesh geometry={nodes.Mesh38_wheel3_0.geometry} material={materials.wheel3} />
        <mesh geometry={nodes.Mesh39_disc2_0.geometry} material={materials.disc2} />
        <mesh geometry={nodes.Mesh40_disc2_0.geometry} material={materials.disc2} />
        <mesh geometry={nodes.Mesh41_califer_0.geometry} material={materials.califer} />
        <mesh geometry={nodes.Mesh41_disc2_0.geometry} material={materials.disc2} />
        <mesh geometry={nodes.Mesh42_disc1_0.geometry} material={materials.disc1} />
        <mesh geometry={nodes.Mesh43_drum1_0.geometry} material={materials.drum1} />
        <mesh geometry={nodes.Mesh44_nut_0.geometry} material={materials.material_23} />
        <mesh geometry={nodes.Mesh45_disc2_0.geometry} material={materials.disc2} />
        <mesh geometry={nodes.Mesh46_disc2_0.geometry} material={materials.disc2} />
        <mesh geometry={nodes.Mesh47_tires_0.geometry} material={materials.tires} />
        <mesh geometry={nodes.Mesh48_wheel2_0.geometry} material={materials.wheel2} />
        <mesh geometry={nodes.Mesh48_wheel1_0.geometry} material={materials.wheel1} />
        <mesh geometry={nodes.Mesh48_wheel3_0.geometry} material={materials.wheel3} />
        <mesh geometry={nodes.Mesh49_disc2_0.geometry} material={materials.disc2} />
        <mesh geometry={nodes.Mesh50_disc2_0.geometry} material={materials.disc2} />
        <mesh geometry={nodes.Mesh51_califer_0.geometry} material={materials.califer} />
        <mesh geometry={nodes.Mesh51_disc2_0.geometry} material={materials.disc2} />
        <mesh geometry={nodes.Mesh52_disc1_0.geometry} material={materials.disc1} />
        <mesh geometry={nodes.Mesh53_drum1_0.geometry} material={materials.drum1} />
        <mesh geometry={nodes.Mesh54_nut_0.geometry} material={materials.material_23} />
        <mesh geometry={nodes.Mesh55_disc2_0.geometry} material={materials.disc2} />
        <mesh geometry={nodes.Mesh56_disc2_0.geometry} material={materials.disc2} />
        <mesh geometry={nodes.Mesh57_tires_0.geometry} material={materials.tires} />
        <mesh geometry={nodes.Mesh58_wheel2_0.geometry} material={materials.wheel2} />
        <mesh geometry={nodes.Mesh58_wheel1_0.geometry} material={materials.wheel1} />
        <mesh geometry={nodes.Mesh58_wheel3_0.geometry} material={materials.wheel3} />
        <mesh geometry={nodes.Mesh59_disc2_0.geometry} material={materials.disc2} />
        <mesh geometry={nodes.Mesh60_disc2_0.geometry} material={materials.disc2} />
        <mesh geometry={nodes.Mesh61_califer_0.geometry} material={materials.califer} />
        <mesh geometry={nodes.Mesh61_disc2_0.geometry} material={materials.disc2} />
        <mesh geometry={nodes.Mesh62_disc1_0.geometry} material={materials.disc1} />
        <mesh geometry={nodes.Mesh63_drum1_0.geometry} material={materials.drum1} />
        <mesh geometry={nodes.Mesh64_nut_0.geometry} material={materials.material_23} />
        <mesh geometry={nodes.Mesh65_disc2_0.geometry} material={materials.disc2} />
        <mesh geometry={nodes.Mesh66_disc2_0.geometry} material={materials.disc2} />
        <mesh geometry={nodes.Mesh67_tires_0.geometry} material={materials.tires} />
        <mesh geometry={nodes.Mesh68_wheel2_0.geometry} material={materials.wheel2} />
        <mesh geometry={nodes.Mesh68_wheel1_0.geometry} material={materials.wheel1} />
        <mesh geometry={nodes.Mesh68_wheel3_0.geometry} material={materials.wheel3} />
        <mesh geometry={nodes.Mesh69_disc2_0.geometry} material={materials.disc2} />
        <mesh geometry={nodes.Mesh70_disc2_0.geometry} material={materials.disc2} />
        <mesh geometry={nodes.Mesh71_califer_0.geometry} material={materials.califer} />
        <mesh geometry={nodes.Mesh71_disc2_0.geometry} material={materials.disc2} />
        <mesh geometry={nodes.Mesh72_disc1_0.geometry} material={materials.disc1} />
        <mesh geometry={nodes.Mesh73_drum1_0.geometry} material={materials.drum1} />
        <mesh geometry={nodes.Mesh74_nut_0.geometry} material={materials.material_23} />
        <mesh geometry={nodes.Mesh75_disc2_0.geometry} material={materials.disc2} />
        <mesh geometry={nodes.Mesh76_disc2_0.geometry} material={materials.disc2} />
      </group>
    </group>
  )
}

useGLTF.preload('/3dmodel/pols_gtr.glb')
